//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartNewspaper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preference
    {
        public long ItemID { get; set; }
        public long UserID { get; set; }
        public double Rating { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual User User { get; set; }
    }
}
