//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartNewspaper
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClusterCentroid
    {
        public int ClusterID { get; set; }
        public string Centroid { get; set; }
    
        public virtual Cluster Cluster { get; set; }
    }
}
