//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartNewspaper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cluster
    {
        public Cluster()
        {
            this.Items = new HashSet<Item>();
        }
    
        public int ClusterID { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public long CategoryID { get; set; }
    
        public virtual Category Categories { get; set; }
        public virtual ICollection<Item> Items { get; set; }
        public virtual ClusterCentroid ClusterCentroid { get; set; }

        public override string ToString()
        {
            return "to be implemeneted";
        }
    }
}
