//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartNewspaper
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class iEntities : DbContext
    {
        public iEntities()
            : base("name=iEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Cluster> Clusters { get; set; }
        public virtual DbSet<Filter> Filters { get; set; }
        public virtual DbSet<IgnoredItem> IgnoredItems { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<ItemsData> ItemsData { get; set; }
        public virtual DbSet<NewsSource> NewsSources { get; set; }
        public virtual DbSet<Preference> Preferences { get; set; }
        public virtual DbSet<ToReadList> ToReadList { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<ItemContent> ItemContents { get; set; }
        public virtual DbSet<ClusterCentroid> ClusterCentroids { get; set; }
    
        public virtual ObjectResult<UserToReadList_Result> UserToReadList(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UserToReadList_Result>("UserToReadList", userIdParameter);
        }
    }
}
