//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartNewspaper
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsSource
    {
        public NewsSource()
        {
            this.Items = new HashSet<Item>();
            this.Users = new HashSet<User>();
        }
    
        public long NewsSourcesID { get; set; }
        public string SourceName { get; set; }
        public string URL { get; set; }
        public string Language { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<Item> Items { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
