//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartNewspaper
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Filters = new HashSet<Filter>();
            this.IgnoredItems = new HashSet<IgnoredItem>();
            this.Preferences = new HashSet<Preference>();
            this.ToReadList = new HashSet<ToReadList>();
            this.NewsSources = new HashSet<NewsSource>();
        }
    
        public long UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string ssd { get; set; }
        public string FacebookProfile { get; set; }
        public string UserPic { get; set; }
        public string LongTermProfile { get; set; }
        public Nullable<System.DateTime> ProfileLastUpdate { get; set; }
        public string ShortTermProfile { get; set; }
    
        public virtual ICollection<Filter> Filters { get; set; }
        public virtual ICollection<IgnoredItem> IgnoredItems { get; set; }
        public virtual ICollection<Preference> Preferences { get; set; }
        public virtual ICollection<ToReadList> ToReadList { get; set; }
        public virtual ICollection<NewsSource> NewsSources { get; set; }

        public override string ToString()
        {
            return string.Join(";", new string[] { UserName, Password, FirstName, LastName, Email, UserPic, UserID.ToString() });
        }
    }
}
